### ISSUE TITLE
Error using xmlread on standalone versions of Fmask

### ISSUE THREAD

**Issue by begreeen** [GERSL/Fmask4#26]
Hi,
I'm able to run Fmas using Matlab source code, however not standalone versions (neither on Linux - WSL2/Docker nor Windows). I have the same error as below, on different versions of Fmask 4.x. Do you have an idea if this is a problem with Fmask or rather runtime? 

```
Fmask 4.5 start ...
Cloud/cloud shadow/snow dilated by 3/3/0 pixels.
Cloud probability threshold of 20.00%.
Load or calculate TOA reflectances.
Error using xmlread (line 116)
Java exception occurred:
org.xml.sax.SAXParseException; systemId: file:/work/a.SAFE/; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
        at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
        at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentScannerImpl$PrologDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)

Error in xml2struct (line 53)

Error in ReadS2RadiometricOffset (line 10)

Error in LoadData (line 52)

Error in autoFmask (line 122)

Error in Fmask_4_5 (line 72)

MATLAB:Java:GenericException
```

Thanks!

**Comment by sqwev** [comment]
Excuse me, I have the same problem in Fmask4.6, do you fix this problem?

**Comment by leleist** [comment]
I encounter the same issue with Fmask4.5 on Windows.
